-- NOTES TABLE
create table if not exists notes (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  title text,
  content text,
  summary text,
  metadata jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);