-- NOTIFICATION SETTINGS TABLE
create table if not exists notification_settings (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  note_id bigint references notes(id) on delete cascade,
  notify boolean default false,
  notify_type text check (notify_type in ('hourly', 'daily')),
  notify_time text,  -- 'HH:MM' for daily
  end_date timestamptz,  -- End date for notifications
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- PUSH SUBSCRIPTIONS TABLE (Updated for FCM)
create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references users(id) on delete cascade,
  fcm_token text unique,  -- FCM token for Firebase Cloud Messaging
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);